apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
spec:
  capacity:
    storage: {{ .Values.volumeSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: {{ .Release.Name }}-pvc
  # Affinity
  {{- if .Values.nodeAffinity.enabled }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        {{- range .Values.nodeAffinity.preferredNodes }}
        - matchExpressions:
          {{- range $key, $value := .labels }}
          - key: {{ $key }}
            operator: In
            values:
              - {{ $value }}
          {{- end }}
        {{- end }}
  {{- end }}