apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-server-pv
spec:
  capacity:
    storage: {{ .Values.volumeSize }}
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: {{ .Values.volumeHandle }}
    volumeAttributes:
      numberOfReplicas: {{ .Values.numberOfReplicas }}
  persistentVolumeReclaimPolicy: Retain
