apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-server-volume-minio-server-statefulset-0
  namespace: minio-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.volumeSize }}
  volumeName: minio-server-pv
