apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace | default .Values.namespace }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.username | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.password | b64enc }}
