apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: 9000
      name: http
    - port: 9001
      name: console
  clusterIP: None
  selector:
    app: {{ .Release.Name }}
