apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- range .Values.nodeAffinity.preferredNodes }}
          - weight: {{ .weight }}
            preference:
              matchExpressions:
              {{- range $key, $value := .labels }}
              - key: {{ $key }}
                operator: In
                values:
                - {{ $value }}
              {{- end }}
          {{- end }}
      {{- end }}