apiVersion: v1
entries:
  factorio-server:
  - apiVersion: v2
    appVersion: 2.0.32
    created: "2025-02-05T17:40:41.502154+01:00"
    description: A Helm chart for Factorio server
    digest: 31d5f71e4a1d9ed8c0f25dc4f68918b778ef5c48c381ee983ff15e5d149bfde0
    name: factorio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/factorio-server-1.0.8.tgz
    version: 1.0.8
  - apiVersion: v2
    appVersion: 2.0.32
    created: "2025-02-05T17:40:41.501948+01:00"
    description: A Helm chart for Factorio server
    digest: d63ec45a3ee4dff479d047585226dc48d2c589335d681e2ea622763a77a7db16
    name: factorio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/factorio-server-1.0.7.tgz
    version: 1.0.7
  - apiVersion: v2
    appVersion: 2.0.32
    created: "2025-02-05T17:40:41.501729+01:00"
    description: A Helm chart for Factorio server
    digest: ba86428febfd1554d2ddf5533486ca9ac32dd5ba16acf4d768f4ba3debc69895
    name: factorio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/factorio-server-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v2
    appVersion: 2.0.32
    created: "2025-02-05T17:40:41.501512+01:00"
    description: A Helm chart for Factorio server
    digest: c51270d1bdc70489c63dfac148d5f6c13e01548eb19a5e856c03f07c360114d4
    name: factorio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/factorio-server-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v2
    appVersion: 2.0.32
    created: "2025-02-05T17:40:41.501298+01:00"
    description: A Helm chart for Factorio server
    digest: 00f64deb62ec825c20276e98b4774e835514d0c465c324ad074781e60aa3eb17
    name: factorio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/factorio-server-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v2
    appVersion: 2.0.32
    created: "2025-02-05T17:40:41.501087+01:00"
    description: A Helm chart for Factorio server
    digest: 6c5761e1d1c3539c1ae15ef792372ac9926e2c772f93d919b29e067c666c7d59
    name: factorio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/factorio-server-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 2.0.32
    created: "2025-02-05T17:40:41.500815+01:00"
    description: A Helm chart for Factorio server
    digest: 189fd7a86863fdb5a4c06e9a65c4c24356fe55721bc11617f2729bd9bcfa8cd6
    name: factorio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/factorio-server-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 2.0.32
    created: "2025-02-05T17:40:41.499156+01:00"
    description: A Helm chart for Factorio server
    digest: 7be3bd3cdba97aa123676a619783b7f0a039f8f7c4f3ca1750b7fde624411f09
    name: factorio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/factorio-server-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 2.0.28
    created: "2025-02-05T17:40:41.498935+01:00"
    description: A Helm chart for Factorio server
    digest: 6f2dbb882c45f762b127cef2adb5a67168f0b5fa0432cfa8e048567116444d11
    name: factorio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/factorio-server-1.0.0.tgz
    version: 1.0.0
  minio-server:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-02-05T17:40:41.502623+01:00"
    description: A Helm chart for Kubernetes
    digest: 1d0cfee4b4945b6d0725ab36134f3b28d959091d9b4cf1f65c5b1195a149e5b6
    name: minio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/minio-server-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-02-05T17:40:41.502469+01:00"
    description: A Helm chart for Kubernetes
    digest: fcbcf8107453357f55dd8dc5c79e06a965e71636cc07b68df6c201529a0b21cb
    name: minio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/minio-server-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-02-05T17:40:41.502307+01:00"
    description: A Helm chart for Kubernetes
    digest: 77350cd0d0f1fe3e8a1fa85b9d4cbc3a115772558bd69cdbada0cc344ba885ab
    name: minio-server
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/minio-server-1.0.0.tgz
    version: 1.0.0
  test:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-02-05T17:40:41.502984+01:00"
    description: Test Helm chart for Kubernetes
    digest: 9f488f1241beba4c919a97b7f1b9d6e7041fd91f7682ff3f02fda721adfb3cb5
    name: test
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/test-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-02-05T17:40:41.502867+01:00"
    description: Test Helm chart for Kubernetes
    digest: dafab3cc37c32279bd0e35a267c23ddcc56ee1659ea39914297deacbf25b0122
    name: test
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/test-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-02-05T17:40:41.502747+01:00"
    description: Test Helm chart for Kubernetes
    digest: ab6fa87c54ef7c9ed953691092e5911781594c7a5135e7d560f424075d9eff9f
    name: test
    type: application
    urls:
    - https://us2h.github.io/helm-charts/charts/test-1.0.0.tgz
    version: 1.0.0
generated: "2025-02-05T17:40:41.498609+01:00"
