apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-auth-secret
  namespace: {{ .Release.Namespace | default .Values.namespace }}
type: Opaque
data:
  # Generate with: htpasswd -Bbn username password | base64
  htpasswd: dXMyaDokMnkkMDUkOGlsTnBqcUNnVExFaDZITXFtNWl3dXZLREZvanQuNUtYeDBxVFlPWXpZbkQ0N3BwQVJqRm0KCg==
