apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-secret
  namespace: {{ .Release.Namespace | default .Values.namespace }}
type: Opaque
data:
  s3-access-key: {{ .Values.registry.storage.s3.accessKey | b64enc }}
  s3-secret-key: {{ .Values.registry.storage.s3.secretKey | b64enc }}