apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace | default .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
  type: ClusterIP
