apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - name: factorio-udp
      port: {{ .Values.port }}
      protocol: UDP
      targetPort: 34197
    - name: factorio-tcp
      port: {{ .Values.rconPort }}
      protocol: TCP
      targetPort: 27015
  selector:
    app: {{ .Release.Name }}
