apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Release.Name }}-port
      protocol: UDP
      port: {{ .Values.port }}
      targetPort: 34197
  selector:
    app: {{ .Release.Name }}
