apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-statefulset
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.factorioServerImage }}:{{ .Values.version }}
          volumeMounts:
            - mountPath: "/factorio"
              name: {{ .Release.Name }}-volume
          ports:
            - containerPort: 34197
          readinessProbe:
            tcpSocket:
              port: 34197
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.volumeSize }}
