namespace: minio-server

imageVersion: RELEASE.2024-08-03T04-33-23Z

apiDomain: api.example.com
consoleDomain: example.com

username: user
password: pass

volumeSize: 100Gi

nodeAffinity:
  enabled: true
  preferredNodes:
    - labels:
        cpu-type: intel
        size: medium
    - labels:
        cpu-type: n100
        size: medium
    - labels:
        cpu-type: amd
        size: large