namespace: minio-server

imageVersion: RELEASE.2024-08-03T04-33-23Z

apiDomain: api.example.com
consoleDomain: example.com

username: user
password: pass

volumeSize: 100Gi

nodeAffinity:
  enabled: true
  preferredNodes:
    - name: primary
      weight: 100
      labels:
        size: medium
        cpu-type: intel
    - name: secondary
      weight: 50
      labels:
        size: medium
        cpu-type: n100
    - name: fallback
      weight: 25
      labels:
        size: large
        cpu-type: amd
